parsers:
  javascript:
    enable_partials: yes

coverage:
  status:
    project:
      default:
        target: auto
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        flags: unit
