language: node_js

# 2*2 matrix for tests
os:
  - linux
  - windows
node_js:
  - 10
  - 12

jobs:
  include:
    # run tests in latest LTS Node.js release and publish code coverage
    - name: 'Coverage'
      os: linux
      node_js: lts/*
      script:
        - npm run test-unit
        - npm run codecov -- -c -Z -f .coverage/coverage-final.json -F unit

    # create a new release if $CREATE_RELEASE is set
    - stage: Create Release
      if: env(CREATE_RELEASE) = true AND type = api AND tag IS blank
      os: linux
      node_js: 12
      git:
        depth: false # disable --depth
      script:
        # fail-fast using set -e
        - set -e
        # decrypt and ssh-add the deploy-key
        - openssl aes-256-cbc -K $encrypted_05f822b6caa8_key -iv $encrypted_05f822b6caa8_iv
          -in .github/travis-deploy-key.enc -out /tmp/travis-deploy-key -d
        - chmod 600 /tmp/travis-deploy-key
        - eval "$(ssh-agent -s)"
        - ssh-add /tmp/travis-deploy-key
        - rm /tmp/travis-deploy-key
        # convert remote URL from HTTPS to SSH
        - git remote set-url origin $(git config --get remote.origin.url | sed -E 's#(http.*://)([^/]+)/(.+)$#git@\2:\3#g')
        - ssh-keyscan github.com >> ~/.ssh/known_hosts
        # create release
        - npm run release $PUSH_TO_ORIGIN $PRERELEASE_SUFFIX
        - set +e

    # publish npm package on tagged builds
    - stage: Publish Package
      if: tag IS present
      os: linux
      node_js: 12
      git:
        depth: false # disable --depth
      script:
        # fail-fast using set -e
        - set -e
        # get prerelease suffix from version tag
        - TAG=$(echo $TRAVIS_TAG | sed 's/^.*-\([a-z]*\).*$/\1/')
        # set to `latest` in case of no suffix
        - TAG=$([ "${TAG}" = "$TRAVIS_TAG" ] && echo "latest" || echo $TAG)
        # make sure `latest` tag is create from main branch
        - '[ "$TAG" = "latest" ] && [ $(git rev-parse HEAD) != $(git rev-parse origin/main) ] && return 1 || return 0'
        - set +e
      deploy:
        edge: true # opt in to dpl v2
        provider: npm
        tag: $TAG
        on:
          tags: true
          all_branches: true

    # update gh-pages docs on main
    - stage: Publish Docs
      if: branch = main
      script: npm run build-docs
      before_deploy: openssl aes-256-cbc -K $encrypted_05f822b6caa8_key -iv $encrypted_05f822b6caa8_iv
        -in .github/travis-deploy-key.enc -out /tmp/travis-deploy-key -d
      deploy:
        edge: true # opt in to dpl v2
        provider: pages:git
        local_dir: out/docs
        keep_history: false
        deploy_key: /tmp/travis-deploy-key
        commit_message: Deploy to %{target_branch}
        on:
          branch: main

before_install:
  - '[[ "$CREATE_RELEASE" == "true" || "$TRAVIS_BRANCH" == "main" ]] && true || unset encrypted_05f822b6caa8_key'
  - '[[ "$CREATE_RELEASE" == "true" || "$TRAVIS_BRANCH" == "main" ]] && true || unset encrypted_05f822b6caa8_iv'
  - '[[ -z "$TRAVIS_TAG" ]] && unset NPM_API_TOKEN || true'

notifications:
  slack:
    secure: PuYBCkRXgUKxoFMyTZdYcxplpgW+T/hxq54gsFOcAxN079i7PTD/GmGIgKM1RviCocvroUst5bW3ULk3haYUb8gQSCyAeHzRl00DaoOXshTRjFzJyU6m5wbT/R45dh6ZO2BT6uwlVU95KznieCC+yjlbppPOis8bwxra08ODnsA1L7OeI7fVlKjyh+lPA4qnmuYpNtMfTO5mmHroHBS5nWoB1WctWuZQGSfDYLUr/XrhKkJOBbv7FI7setTroIRF4Rs9nIFEF3mzTuUK5VV6lQAZRzNHKmgD9DmGVeaB5Y4fWEznocV1d6cInsjMr4EyMYziyOFnnPZAk8GZapMDwD0/5E9L5+Q8uXhFhVHYurpZnP+wylqZmnfb4UaFcP96BBaavhfF/ai+LWlLbHiL5b1HX4dlauNfHdq1W1YCILI2Atfr+36rqu3102S6HHkOssoTw09ftLfQHuF6CNYnVE5cS40pupwFZj3o0h9yQnCFDPxlq2ls+hon+PKL9wCHL5MlG+jQZDDL8eZC8F9CoZUyVIxNhoh0fnZ+t4bIlGW5eB8f8oMCxcnjocxZpichfAsmuaPh/e2KfdoF/B7ce6+Tb3/YXqo5QVTsJ1Vzi4I7c3jx1Q0DAyZODsBKyE0y7NfmeVNap0WIgajiJBoKji8Fjw+tDfa3hSb4yyPSG6w=
  webhooks:
    urls:
      secure: vT8yu7tdMzqXk0PHzXyH6vOlU4WnJbfMe0IvlJcwgc/OUdOQaSdAGcBSbAgy3fDk7Ya/WLSAwSzBTLJ6SFXE7UFp0Govu7aSoS/33Xi5GLrS10CA8QPqRbj8cJRLin0WSs0R3vP4F52dSdsE9D281eu6KDFuMNz/St63dSVde+9i5RgVWvTDCNBiLkAMTWgy+B41kVBOaajK/cXjzzAMxzHrMEX/v9GUkrSMyTJ+GWdS3m2cAjaRI/loKDD0SZqdGpeg9ZTRBSBCUaPjYLHe/7eVBGWitn4WgJP81ZmtukjIUi1WuEN6lrX67pNEWXI2TJqaCY/a57Nq9ikVW3w0GRnHBfUb/PYwebTCSSUUmvCdTVuH9x5fnZhnHo7f3yODT8p7G//hfEZ8Pd6FTRULOyxSnc1mqnKusqqFjPX4l8RbG43hWy/ch7xW8/AP7MjiIG69YNrjm/FEfQ3qId6EACL9lzIwS4au2FKvjiXyNAWBoNbUmwDLu95y5HSxl+/E5KIN+S/37NhFQTwUFzXKscrEe9dmaeaGYWlYyyTmSw8eh65wQm9jN1iUfy8xhrZZYm5mFH1oKAYpOtUtMVEa0ofS6tfhRKb05qJxihcudcuQYgpuYYoWmK1xU18HAe6WnLiZ/1DP+aUeZY12DZFaAZzFt0DzIsCLQmiu1CrRItM=
